[build]
  command = "npm start"  # Specify the build command for npm
  publish = "public"          # Specify the publish directory
  functions = "functions"  # Directory with the serverless Lambda functions